/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { ItemsPedido } from './itemsPedido';
import type { Usuario } from './usuario';

export interface Pedido {
  id?: number;
  usuarioId?: number;
  fecha?: string;
  total?: number;
  /** @nullable */
  estado?: string | null;
  /** @nullable */
  itemsPedidos?: ItemsPedido[] | null;
  usuario?: Usuario;
}
