/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { ItemsPedido } from './itemsPedido';

export interface Personalizacione {
  id?: number;
  itemPedidoId?: number;
  /** @nullable */
  imagenCliente?: string | null;
  /** @nullable */
  mockupGenerado?: string | null;
  itemPedido?: ItemsPedido;
}
