/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { ItemsPedido } from './itemsPedido';

export interface Producto {
  id?: number;
  /** @nullable */
  nombre?: string | null;
  /** @nullable */
  descripcion?: string | null;
  precio?: number;
  /** @nullable */
  categoria?: string | null;
  /** @nullable */
  imagenUrl?: string | null;
  personalizable?: boolean;
  /** @nullable */
  itemsPedidos?: ItemsPedido[] | null;
}
