/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */

export type RolUsuario = typeof RolUsuario[keyof typeof RolUsuario];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolUsuario = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
