/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { RolUsuario } from './rolUsuario';
import type { Pedido } from './pedido';

export interface Usuario {
  id?: number;
  /** @nullable */
  nombre?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  passwordHash?: string | null;
  rol?: RolUsuario;
  /** @nullable */
  pedidos?: Pedido[] | null;
  emailVerificado?: boolean;
  /** @nullable */
  codigoVerificacion?: string | null;
}
