/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */

export interface VerifyEmailDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  codigo?: string | null;
}
