// <auto-generated />
using System;
using Acceso_datos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acceso_datos.Migrations
{
    [DbContext(typeof(ViajedetintaContext))]
    partial class ViajedetintaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acceso_datos.Models.ItemsPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ItemsPed__3214EC0780459EBD");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsPedido", (string)null);
                });

            modelBuilder.Entity("Acceso_datos.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Pedidos__3214EC07CD32F60C");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Acceso_datos.Models.Personalizacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagenCliente")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ItemPedidoId")
                        .HasColumnType("int");

                    b.Property<string>("MockupGenerado")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK__Personal__3214EC071772AE3C");

                    b.HasIndex(new[] { "ItemPedidoId" }, "UQ__Personal__8433C88E3746C37B")
                        .IsUnique();

                    b.ToTable("Personalizaciones");
                });

            modelBuilder.Entity("Acceso_datos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Personalizable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC07142C0072");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Acceso_datos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC0769F1746E");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D1053401FB641E")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Acceso_datos.Models.ItemsPedido", b =>
                {
                    b.HasOne("Acceso_datos.Models.Pedido", "Pedido")
                        .WithMany("ItemsPedidos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemsPedi__Pedid__4316F928");

                    b.HasOne("Acceso_datos.Models.Producto", "Producto")
                        .WithMany("ItemsPedidos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemsPedi__Produ__440B1D61");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Acceso_datos.Models.Pedido", b =>
                {
                    b.HasOne("Acceso_datos.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Pedidos__Usuario__403A8C7D");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Acceso_datos.Models.Personalizacione", b =>
                {
                    b.HasOne("Acceso_datos.Models.ItemsPedido", "ItemPedido")
                        .WithOne("Personalizacione")
                        .HasForeignKey("Acceso_datos.Models.Personalizacione", "ItemPedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__Personali__ItemP__47DBAE45");

                    b.Navigation("ItemPedido");
                });

            modelBuilder.Entity("Acceso_datos.Models.ItemsPedido", b =>
                {
                    b.Navigation("Personalizacione");
                });

            modelBuilder.Entity("Acceso_datos.Models.Pedido", b =>
                {
                    b.Navigation("ItemsPedidos");
                });

            modelBuilder.Entity("Acceso_datos.Models.Producto", b =>
                {
                    b.Navigation("ItemsPedidos");
                });

            modelBuilder.Entity("Acceso_datos.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
